export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_BY_QUANTITY = "GET_PRODUCTS_BY_QUANTITY";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
